name: dir-looping

on:
  push:
    branches: 
      - test2

jobs:
  collect-directories:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: get directories
        run: ./scripts/get-directories.sh
