name: learn stuff

on:
  push:
    branches:
      - main

jobs:
  explore:
    runs-on: ubuntu-latest

    steps:

      - name: look at env vars
        run: |
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          git clone git@github.com:$GITHUB_REPOSITORY

      # https://github.com/actions/checkout
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
