name: test

on:
  push:
    branches: 
      - test

jobs:
  kustomize-stuff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run kubernetes tools
      uses: stefanprodan/kube-tools@v1.7.1
      with:
        command: |
          echo "Run conftest"
          kustomize build workloads/hello | conftest test -p test/policy -
          #echo "Run kubeval"
          #helmv3 template ./charts/test | kubeval --strict


    - run: kustomize version

